### ISSUE TITLE
 Bootstrap error

### ISSUE THREAD

**Issue by nefera606** [nuls-io/nuls#18]
```./start.sh 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
10:54:17,862 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:54:17,862 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:54:17,862 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/inigo/projects/nuls/node/target/conf/logback.xml]
10:54:17,911 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:54:17,915 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:54:17,917 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:54:17,971 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:54:17,973 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
10:54:17,981 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@22:26 - no applicable action for [MaxFileSize], current ElementPath  is [[configuration][appender][rollingPolicy][MaxFileSize]]
10:54:17,983 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
10:54:17,984 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern ./logs/nuls.%d{yyyy-MM-dd}.log for the active file
10:54:17,987 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern './logs/nuls.%d{yyyy-MM-dd}.log'.
10:54:17,987 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
10:54:17,989 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Wed Feb 28 10:54:17 CET 2018
10:54:17,990 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: ./logs/nuls.2018-02-28.log
10:54:17,990 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
10:54:17,991 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
10:54:17,991 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:54:17,992 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
10:54:17,992 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.ibatis] to INFO
10:54:17,992 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.ibatis] to false
10:54:17,992 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.nuls.db.dao.impl.mybatis.mapper] to INFO
10:54:17,992 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [io.nuls.db.dao.impl.mybatis.mapper] to false
10:54:17,992 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:54:17,993 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@531be3c5 - Registering current configuration as safe fallback point

2018-02-28 10:54:17.999 [Nuls] ERROR io.nuls.core.utils.log.Log - io.nuls.Bootstrap.main(Bootstrap.java:51):
io.nuls.core.exception.NulsException: 操作失败
	at io.nuls.core.utils.log.Log.error(Log.java:221) ~[core-1.0-SNAPSHOT.jar:na]
	at io.nuls.Bootstrap.main(Bootstrap.java:51) [nuls-node.jar:na]
Caused by: java.lang.NullPointerException: null
	at io.nuls.core.utils.spring.lite.utils.ScanUtil.findClassJar(ScanUtil.java:88) ~[core-1.0-SNAPSHOT.jar:na]
	at io.nuls.core.utils.spring.lite.utils.ScanUtil.scan(ScanUtil.java:66) ~[core-1.0-SNAPSHOT.jar:na]
	at io.nuls.core.utils.spring.lite.core.SpringLiteContext.init(SpringLiteContext.java:59) ~[core-1.0-SNAPSHOT.jar:na]
	at io.nuls.core.MicroKernelBootstrap.init(MicroKernelBootstrap.java:74) ~[core-1.0-SNAPSHOT.jar:na]
	at io.nuls.Bootstrap.sysStart(Bootstrap.java:59) [nuls-node.jar:na]
	at io.nuls.Bootstrap.main(Bootstrap.java:49) [nuls-node.jar:na] ```

**Comment by niels1286** [comment]
thx,we will fix it.
